---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/10/1 11:51 AM
---

package.cpath = "./?.lua"

local Cpidmap = require("pidmap")

local m = Cpidmap.new("self", 'x', true)
local res = m:elfInfo(".*libc")
assert(res, "get libc position failed.")
local libc = res[4]
res = m:query(res[1] + 400)
assert(res, "check libc position failed.")
assert(libc == res[4], "check libc name failed.")
